In [26]:
# %% make repo root importable (so `from src...` works)
import sys
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))
print("root on path:", ROOT)

root on path: /Users/admin/Desktop/carbon-portfolio-project-v2

In [27]:
# %% auto-reload edited src modules (so src/*.py edits take effect without kernel restart)
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [28]:
import pandas as pd
from src.db import connect
from src.data_download import batch_download_strict_min_points
from src.price_pull import prep_symbols, load_prices, build_symbol_coverage
from src.fx_pull import currencies_in_universe, fetch_fx, load_fx
from src.actions_pull import fetch_actions, load_actions

In [29]:
con = connect(str(ROOT / 'data' / 'carbon.db'))

In [30]:

# %% one-time: apply new prices/fx_rates schema (prices is empty -> safe to drop)
con.executescript((ROOT / 'sql' / 'schema.sql').read_text())

### Stock price pulls

In [55]:

# %% Section 1 — symbol prep (inspect, confirm before pulling)
ok, unmapped = prep_symbols(con)

tickers total     : 8,179
mapped to yahoo   : 6,406
unmapped exchange : 1,773
currency mix      :
currency
EUR    2647
GBp    1268
PLN     695
SEK     660
RON     294
NOK     243
CHF     204
USD     146
DKK     134
HUF      62
CZK      21
AUD      13
CAD       7
HKD       5
ZAc       3
ISK       2
ILA       2
Unmapped Exchange:
 exchange
Delisted                        724
Bulgarian Stock Exchange        242
Spotlight Stock Market          131
Nordic Growth Market (NGM)       93
Mercado Alternativo Bursatil     91
Cyprus Stock Exchange            85
Zagreb Stock Exchange            65
Malta Stock Exchange             53
OTC Bulletin Board               37
Norvegian OTC                    36

In [39]:
# %% SMOKE TEST — 50 symbols only, confirm the path before the full backfill
symbol_to_id  = dict(zip(ok['yahoo_symbol'], ok['company_id']))
symbol_to_ccy = dict(zip(ok['yahoo_symbol'], ok['currency']))

smoke = ok['yahoo_symbol'].head(50).tolist()

smoke_df, smoke_short, smoke_never = batch_download_strict_min_points(
    tickers    = smoke,
    start      = "2013-01-01", end = "2025-06-30",
    auto_adjust= False,
    batch_size = 50, pause = 20, min_count = 6,
    output_csv = None, no_data_csv = None,
)
load_prices(con, smoke_df, symbol_to_id, symbol_to_ccy)

Total tickers to process: 50
Downloading batch 0 to 49 / 49

Tickers with < 6 non-NaN Close values: []

Final: 50 tickers with >= 6 data, 0 with too little data, 0 never returned any data.
prices upserted: 162,000 rows, 50 companies

In [60]:
# %% Section 2 — price backfill (auto_adjust=False -> raw prices)
filtered_df, too_short, never_seen = batch_download_strict_min_points(
    tickers    = ok['yahoo_symbol'].tolist(),
    start      = "2013-01-01", end = "2026-06-30",
    auto_adjust= False,
    batch_size = 50, pause = 20, min_count = 6,
    output_csv = "prices_backfill.csv",
    no_data_csv= "prices_missing.csv",
)

Total tickers to process: 6406
Downloading batch 0 to 49 / 6405
Downloading batch 50 to 99 / 6405
Downloading batch 100 to 149 / 6405
Downloading batch 150 to 199 / 6405
Downloading batch 200 to 249 / 6405

$094124453.BR: possibly delisted; no timezone found

1 Failed download:
['094124453.BR']: possibly delisted; no timezone found

Downloading batch 250 to 299 / 6405

$ELN.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$TALD.RO: possibly delisted; no timezone found
$CDSYS.BD: possibly delisted; no timezone found
$MLAST.PA: possibly delisted; no timezone found
$RY8.DU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

5 Failed downloads:
['ELN.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['TALD.RO', 'CDSYS.BD', 'MLAST.PA']: possibly delisted; no timezone found
['RY8.DU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 300 to 349 / 6405

$K2LT.VS: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$VSC.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$4SCI.VI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MLJDL.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$AUXI.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$GREEN.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$PAC.WA: possibly delisted; no timezone found
$PHLOG-B.ST: possibly delisted; no timezone found
$HELIO.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

9 Failed downloads:
['K2LT.VS', 'AUXI.RO', 'GREEN.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['VSC.F']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['4SCI.VI', 'HELIO.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['MLJDL.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['PAC.WA', 'PHLOG-B.ST']: possibly delisted; no timezone found

Downloading batch 350 to 399 / 6405

$BTF.WA: possibly delisted; no timezone found
$MLIPO.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$TNT.WA: possibly delisted; no timezone found
$VVPR: possibly delisted; no timezone found
$FMAR.RO: possibly delisted; no timezone found
$VALBERG.BD: possibly delisted; no timezone found
$DUR.AT: possibly delisted; no timezone found
$SCIBH.MC: possibly delisted; no timezone found
$EGN.MI: possibly delisted; no timezone found

9 Failed downloads:
['BTF.WA', 'TNT.WA', 'VVPR', 'FMAR.RO', 'VALBERG.BD', 'DUR.AT', 'SCIBH.MC', 'EGN.MI']: possibly delisted; no timezone found
['MLIPO.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 400 to 449 / 6405

$QRT.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MLVRF.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$CST.WA: possibly delisted; no timezone found
$HDW-B.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

4 Failed downloads:
['QRT.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['MLVRF.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['CST.WA']: possibly delisted; no timezone found
['HDW-B.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 450 to 499 / 6405

$SCWEL.MC: possibly delisted; no timezone found
$MAHA-A.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$93M.F: possibly delisted; no timezone found
$SPEQT.ST: possibly delisted; no timezone found
$R1B.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MLCOE.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$GG_FERR.L: possibly delisted; no timezone found
$RIIC.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MLOKP.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

9 Failed downloads:
['SCWEL.MC', '93M.F', 'SPEQT.ST', 'GG_FERR.L']: possibly delisted; no timezone found
['MAHA-A.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['R1B.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['MLCOE.PA', 'RIIC.L', 'MLOKP.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 500 to 549 / 6405

$MLEDS.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$DE.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$SPARK.CO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ISD.WA: possibly delisted; no timezone found
$SCLIS.MC: possibly delisted; no timezone found

5 Failed downloads:
['MLEDS.PA', 'DE.ST', 'SPARK.CO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['ISD.WA', 'SCLIS.MC']: possibly delisted; no timezone found

Downloading batch 550 to 599 / 6405

$PMA.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MIG.WA: possibly delisted; no timezone found
$HMSG.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
$EFCUPFFT.TL: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$CINIS.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$DRZ.WA: possibly delisted; no timezone found

6 Failed downloads:
['PMA.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['MIG.WA', 'DRZ.WA']: possibly delisted; no timezone found
['HMSG.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
['EFCUPFFT.TL']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['CINIS.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 600 to 649 / 6405

$AGU.MI: possibly delisted; no timezone found
$MECA.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$EEMS.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$VFA.WA: possibly delisted; no timezone found
$HRC.CO: possibly delisted; no timezone found
$NTQ.L: possibly delisted; no timezone found
$MLASO.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$EEX.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$RCVR.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

9 Failed downloads:
['AGU.MI', 'VFA.WA', 'HRC.CO', 'NTQ.L']: possibly delisted; no timezone found
['MECA.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['EEMS.MI', 'RCVR.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['MLASO.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['EEX.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 650 to 699 / 6405

$DFH.WA: possibly delisted; no timezone found
$MLARI.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MTE.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

3 Failed downloads:
['DFH.WA']: possibly delisted; no timezone found
['MLARI.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['MTE.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 700 to 749 / 6405

$PPG.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$THRG.L: possibly delisted; no timezone found
$M14.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$SGD.WA: possibly delisted; no timezone found
$GSR.MI: possibly delisted; no timezone found
$ATOMT.PR: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$AAAP.L: possibly delisted; no timezone found
$TIGH.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")

8 Failed downloads:
['PPG.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['THRG.L', 'SGD.WA', 'GSR.MI', 'AAAP.L']: possibly delisted; no timezone found
['M14.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['ATOMT.PR']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['TIGH.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")

Downloading batch 750 to 799 / 6405

$MPH.L: possibly delisted; no timezone found
$ALCQ.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$MLCAN.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$G6P.F: possibly delisted; no timezone found
$HRGI.OL: possibly delisted; no timezone found
$HEN.WA: possibly delisted; no timezone found
$BSA.WA: possibly delisted; no timezone found
$TWEP.MI: possibly delisted; no timezone found
$RLF.SW: possibly delisted; no timezone found

9 Failed downloads:
['MPH.L', 'G6P.F', 'HRGI.OL', 'HEN.WA', 'BSA.WA', 'TWEP.MI', 'RLF.SW']: possibly delisted; no timezone found
['ALCQ.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['MLCAN.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 800 to 849 / 6405

$KMB.WA: possibly delisted; no timezone found
$CFM.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$GOV.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$NORD.CO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

4 Failed downloads:
['KMB.WA']: possibly delisted; no timezone found
['CFM.MI', 'GOV.WA', 'NORD.CO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 850 to 899 / 6405

$CMOTEC-B.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$EVRH.L: possibly delisted; no timezone found
$FFP.WA: possibly delisted; no timezone found
$RTOP.L: possibly delisted; no timezone found

4 Failed downloads:
['CMOTEC-B.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['EVRH.L', 'FFP.WA', 'RTOP.L']: possibly delisted; no timezone found

Downloading batch 900 to 949 / 6405

$MLGLA.PA: possibly delisted; no timezone found
$DPG.WA: possibly delisted; no timezone found
$MLIME.PA: possibly delisted; no timezone found
$UBM.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

4 Failed downloads:
['MLGLA.PA', 'DPG.WA', 'MLIME.PA']: possibly delisted; no timezone found
['UBM.MI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 950 to 999 / 6405

$VRL.DU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$01156.HK: possibly delisted; no timezone found
$SBDS.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
$FINEXT.BD: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

4 Failed downloads:
['VRL.DU', 'FINEXT.BD']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['01156.HK']: possibly delisted; no timezone found
['SBDS.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 1000 to 1049 / 6405

$UPRR.RO: possibly delisted; no timezone found
$QUART.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MLBAR.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MASHUP.ST: possibly delisted; no timezone found
$ZS4.MU: possibly delisted; no timezone found

5 Failed downloads:
['UPRR.RO', 'MASHUP.ST', 'ZS4.MU']: possibly delisted; no timezone found
['QUART.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['MLBAR.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 1050 to 1099 / 6405

$BIG1.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MLNOX.PA: possibly delisted; no timezone found
$BGB.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$TBX0.BE: possibly delisted; no timezone found
$MLINM.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$SCM.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

6 Failed downloads:
['BIG1.F', 'BGB.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['MLNOX.PA', 'TBX0.BE']: possibly delisted; no timezone found
['MLINM.PA', 'SCM.MI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 1100 to 1149 / 6405

$YAYTRD.ST: possibly delisted; no timezone found
$LAUR.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MOV-BTU.ST: possibly delisted; no timezone found

3 Failed downloads:
['YAYTRD.ST', 'MOV-BTU.ST']: possibly delisted; no timezone found
['LAUR.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1150 to 1199 / 6405

$AAQ.F: possibly delisted; no timezone found
$COOLKLIMA.BD: possibly delisted; no timezone found
$FING-B.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$SLB.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

4 Failed downloads:
['AAQ.F', 'COOLKLIMA.BD']: possibly delisted; no timezone found
['FING-B.ST', 'SLB.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MLORB.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 1200 to 1249 / 6405

$SEC.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MLGSH.LS: possibly delisted; no timezone found
$ASTG-MTF-B.ST: possibly delisted; no timezone found
$PIIPPO.HE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$MLARR.LS: possibly delisted; no timezone found
$BPU.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

7 Failed downloads:
['MLORB.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['SEC.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['MLGSH.LS', 'ASTG-MTF-B.ST', 'MLARR.LS']: possibly delisted; no timezone found
['PIIPPO.HE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['BPU.SG']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1250 to 1299 / 6405

$LASIA.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MAZ.WA: possibly delisted; no timezone found
$IRP.HM: possibly delisted; no timezone found
$CIVITA.BD: possibly delisted; no timezone found
$MLUAV.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MPK.AT: possibly delisted; no timezone found
$RTC.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$SCORE.MC: possibly delisted; no timezone found

8 Failed downloads:
['LASIA.MI', 'RTC.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['MAZ.WA', 'IRP.HM', 'CIVITA.BD', 'MPK.AT', 'SCORE.MC']: possibly delisted; no timezone found
['MLUAV.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1300 to 1349 / 6405

$MLEFA.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MLNDG.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MET.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$VERI.ST: possibly delisted; no timezone found
$SCSOL.MC: possibly delisted; no timezone found
$NSCI.L: possibly delisted; no timezone found
$OP: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

7 Failed downloads:
['MLEFA.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['MLNDG.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['MET.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['VERI.ST', 'SCSOL.MC', 'NSCI.L']: possibly delisted; no timezone found
['OP']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MLVRE.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 1350 to 1399 / 6405

$BIDS.L: possibly delisted; no timezone found
$TRH.MC: possibly delisted; no timezone found
$MECE.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ELLWEE.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$BWIDL.OL: possibly delisted; no timezone found

6 Failed downloads:
['MLVRE.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['BIDS.L', 'TRH.MC', 'BWIDL.OL']: possibly delisted; no timezone found
['MECE.RO', 'ELLWEE.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 1400 to 1449 / 6405

$ALVER.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$PDA.F: possibly delisted; no timezone found
$VQLA.MU: possibly delisted; no timezone found
$MLMCA.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$NN6.HM: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$XDD.WA: possibly delisted; no timezone found

6 Failed downloads:
['ALVER.PA', 'MLMCA.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['PDA.F', 'VQLA.MU', 'XDD.WA']: possibly delisted; no timezone found
['NN6.HM']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1450 to 1499 / 6405

$VMX.WA: possibly delisted; no timezone found

1 Failed download:
['VMX.WA']: possibly delisted; no timezone found
$MLMIV.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 1500 to 1549 / 6405

$LSAI.L: possibly delisted; no timezone found
$MODEL-B.ST: possibly delisted; no timezone found
$MLSPI.PA: possibly delisted; no timezone found

4 Failed downloads:
['MLMIV.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['LSAI.L', 'MODEL-B.ST', 'MLSPI.PA']: possibly delisted; no timezone found

Downloading batch 1550 to 1599 / 6405

$FFI.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$VMED.DU: possibly delisted; no timezone found

2 Failed downloads:
['FFI.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['VMED.DU']: possibly delisted; no timezone found

Downloading batch 1600 to 1649 / 6405

$A8N.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$DGN.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$RGL.WA: possibly delisted; no timezone found
$PTE.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$KLK.WA: possibly delisted; no timezone found
$NR.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

6 Failed downloads:
['A8N.MU', 'NR.MI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['DGN.WA', 'PTE.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['RGL.WA', 'KLK.WA']: possibly delisted; no timezone found

Downloading batch 1650 to 1699 / 6405

$VRS.L: possibly delisted; no timezone found
$ALCAB.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$HER.WA: possibly delisted; no timezone found
$ALGW.L: possibly delisted; no timezone found
$LBRT.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

5 Failed downloads:
['VRS.L', 'HER.WA', 'ALGW.L']: possibly delisted; no timezone found
['ALCAB.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['LBRT.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 1700 to 1749 / 6405

$HGEA.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MRG.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$FKD.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$CRP.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$YTME.SW: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

5 Failed downloads:
['HGEA.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['MRG.WA', 'FKD.WA', 'CRP.WA', 'YTME.SW']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1750 to 1799 / 6405

$SWEF.L: possibly delisted; no timezone found
$HID.L: possibly delisted; no timezone found
$GRE.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$0K7K.L: possibly delisted; no timezone found
$MCT.L: possibly delisted; no timezone found
$ATO.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

6 Failed downloads:
['SWEF.L', 'HID.L', '0K7K.L', 'MCT.L']: possibly delisted; no timezone found
['GRE.WA', 'ATO.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1800 to 1849 / 6405

$IKIV.L: possibly delisted; no timezone found
$REG.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$REDC.L: possibly delisted; no timezone found
$67R.DU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

4 Failed downloads:
['IKIV.L', 'REDC.L']: possibly delisted; no timezone found
['REG.WA', '67R.DU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 1850 to 1899 / 6405

$AAS.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$BOD.L: possibly delisted; no timezone found
$COR.WA: possibly delisted; no timezone found
$IDM.MI: possibly delisted; no timezone found
$27N.DU: possibly delisted; no timezone found
$FLG.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$AO9.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$KMCP.OL: possibly delisted; no timezone found
$L03.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MB7.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

10 Failed downloads:
['AAS.WA', 'FLG.WA', 'AO9.MU', 'MB7.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['BOD.L', 'COR.WA', 'IDM.MI', '27N.DU', 'KMCP.OL']: possibly delisted; no timezone found
['L03.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 1900 to 1949 / 6405

$PRIN.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$GHS.L: possibly delisted; no timezone found
$PAL.L: possibly delisted; no timezone found
$FOMA.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$TERA.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$A1M.ST: possibly delisted; no timezone found
$LITO.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$OAB.HM: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$TCBP: possibly delisted; no timezone found

9 Failed downloads:
['PRIN.RO', 'FOMA.RO', 'TERA.RO', 'LITO.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['GHS.L', 'PAL.L', 'A1M.ST', 'TCBP']: possibly delisted; no timezone found
['OAB.HM']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 1950 to 1999 / 6405

$DKE.L: possibly delisted; no timezone found
$DDM.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$PXOG.L: possibly delisted; no timezone found
$HELN.SW: possibly delisted; no timezone found

4 Failed downloads:
['DKE.L', 'PXOG.L', 'HELN.SW']: possibly delisted; no timezone found
['DDM.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 2000 to 2049 / 6405

$EBY1.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$DIVI.L: possibly delisted; no timezone found
$BVX.L: possibly delisted; no timezone found
$SMART-SDB.ST: possibly delisted; no timezone found
$FOC.SW: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

5 Failed downloads:
['EBY1.SG', 'FOC.SW']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['DIVI.L', 'BVX.L', 'SMART-SDB.ST']: possibly delisted; no timezone found

Downloading batch 2050 to 2099 / 6405

$REE.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
$A41BVS.DU: possibly delisted; no timezone found
$06160.HK: possibly delisted; no timezone found
$OCTP.L: possibly delisted; no timezone found
$XK7.SG: possibly delisted; no timezone found

5 Failed downloads:
['REE.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
['A41BVS.DU', '06160.HK', 'OCTP.L', 'XK7.SG']: possibly delisted; no timezone found

Downloading batch 2100 to 2149 / 6405

$MLMR.LS: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$NBA.MI: possibly delisted; no timezone found
$BBH.L: possibly delisted; no timezone found

3 Failed downloads:
['MLMR.LS']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['NBA.MI', 'BBH.L']: possibly delisted; no timezone found

Downloading batch 2150 to 2199 / 6405

$O3PNRS.BD: possibly delisted; no timezone found
$QB7.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$PACEU.AS: possibly delisted; no timezone found
$Q9U.DU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ICE.BR: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$RORA.PA: possibly delisted; no timezone found
$BUF.F: possibly delisted; no timezone found
$D77.BE: possibly delisted; no timezone found
$LBH1.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

9 Failed downloads:
['O3PNRS.BD', 'PACEU.AS', 'RORA.PA', 'BUF.F', 'D77.BE']: possibly delisted; no timezone found
['QB7.BE', 'Q9U.DU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['ICE.BR', 'LBH1.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$S1420.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$S3700.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 2200 to 2249 / 6405

$S2490.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$JMG.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
$A283WQ.DU: possibly delisted; no timezone found
$SL051.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MLISP.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

7 Failed downloads:
['S1420.MC', 'S3700.MC', 'S2490.MC', 'SL051.MC', 'MLISP.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['JMG.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
['A283WQ.DU']: possibly delisted; no timezone found

Downloading batch 2250 to 2299 / 6405

$HWC.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")
$S1436.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MLMAC.LS: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$RAY.WA: possibly delisted; no timezone found
$SIV.L: possibly delisted; no timezone found
$S2856.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

6 Failed downloads:
['HWC.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")
['S1436.MC', 'MLMAC.LS', 'S2856.MC']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['RAY.WA', 'SIV.L']: possibly delisted; no timezone found

Downloading batch 2300 to 2349 / 6405

$CDR.MI: possibly delisted; no timezone found
$CTE.WA: possibly delisted; no timezone found
$EGY.WA: possibly delisted; no timezone found

3 Failed downloads:
['CDR.MI', 'CTE.WA', 'EGY.WA']: possibly delisted; no timezone found

Downloading batch 2350 to 2399 / 6405

$SCIG2.MC: possibly delisted; no timezone found
$WRE.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$IRABAS.CO: possibly delisted; no timezone found
$GDS.WA: possibly delisted; no timezone found
$AGCM.RO: possibly delisted; no timezone found

5 Failed downloads:
['SCIG2.MC', 'IRABAS.CO', 'GDS.WA', 'AGCM.RO']: possibly delisted; no timezone found
['WRE.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 2400 to 2449 / 6405

$RAP.PA: possibly delisted; no timezone found
$PGG.WA: possibly delisted; no timezone found
$SCFRS.MC: possibly delisted; no timezone found
$GRL.WA: possibly delisted; no timezone found
$URA.L: possibly delisted; no timezone found
$EFIN.VI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$CARE.VI: possibly delisted; no timezone found
$PSH.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$CTEA.L: possibly delisted; no timezone found
$SCIG5.MC: possibly delisted; no timezone found
$KDEV.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$L3D.DU: possibly delisted; no timezone found
$PRDI.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$DEAR.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

14 Failed downloads:
['RAP.PA', 'PGG.WA', 'SCFRS.MC', 'GRL.WA', 'URA.L', 'CARE.VI', 'CTEA.L', 'SCIG5.MC', 'L3D.DU']: possibly delisted; no timezone found
['EFIN.VI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['PSH.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['KDEV.ST', 'DEAR.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['PRDI.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")

Downloading batch 2450 to 2499 / 6405

$MEBY.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$GHT.WA: possibly delisted; no timezone found
$CE.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$BIG.WA: possibly delisted; no timezone found
$MYNZ: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$FHP.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")

6 Failed downloads:
['MEBY.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['GHT.WA', 'BIG.WA']: possibly delisted; no timezone found
['CE.ST', 'MYNZ']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['FHP.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")

Downloading batch 2500 to 2549 / 6405

$5PG.CO: possibly delisted; no timezone found
$ZICC.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$5OZ.DU: possibly delisted; no timezone found
$SHY.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$RGM.L: possibly delisted; no timezone found
$FAR.WA: possibly delisted; no timezone found
$AFC.L: possibly delisted; no timezone found
$BRH.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

8 Failed downloads:
['5PG.CO', '5OZ.DU', 'RGM.L', 'FAR.WA', 'AFC.L']: possibly delisted; no timezone found
['ZICC.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['SHY.WA', 'BRH.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 2550 to 2599 / 6405

$HOT.L: possibly delisted; no timezone found
$ILK1.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$IC8.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$KIBO.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$GRZ.WA: possibly delisted; no timezone found
$SKY.WA: possibly delisted; no timezone found
$GHIM.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$SCASM.MC: possibly delisted; no timezone found

8 Failed downloads:
['HOT.L', 'GRZ.WA', 'SKY.WA', 'SCASM.MC']: possibly delisted; no timezone found
['ILK1.SG', 'IC8.F', 'KIBO.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['GHIM.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")

Downloading batch 2600 to 2649 / 6405

$WMC.MI: possibly delisted; no timezone found
$HT5.SW: possibly delisted; no timezone found
$9RP.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$IRL.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$N4P.L: possibly delisted; no timezone found
$JMI.L: possibly delisted; no timezone found
$EU-SOLAR.BD: possibly delisted; no timezone found
$ANIM.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")

8 Failed downloads:
['WMC.MI', 'HT5.SW', 'N4P.L', 'JMI.L', 'EU-SOLAR.BD']: possibly delisted; no timezone found
['9RP.SG', 'IRL.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['ANIM.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")

Downloading batch 2650 to 2699 / 6405

$IDG.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$RLIINV.CO: possibly delisted; no timezone found
$C90.DU: possibly delisted; no timezone found
$BONEH.HE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$HRU.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$IDOGEN.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$ICMA.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$SIEP.RO: possibly delisted; no timezone found
$LA2.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MLCOT.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$CYK.L: possibly delisted; no timezone found

11 Failed downloads:
['IDG.WA', 'BONEH.HE', 'LA2.BE', 'MLCOT.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['RLIINV.CO', 'C90.DU', 'SIEP.RO', 'CYK.L']: possibly delisted; no timezone found
['HRU.MU', 'IDOGEN.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['ICMA.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$S0063.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 2700 to 2749 / 6405

$M5S.HM: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$CLINE-B.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$VAI.WA: possibly delisted; no timezone found
$PELA.RO: possibly delisted; no timezone found
$DIABIO.MU: possibly delisted; no timezone found
$S2963.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$MINI.L: possibly delisted; no timezone found
$EDL.L: possibly delisted; no timezone found
$XX1.HM: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ANA.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

11 Failed downloads:
['S0063.MC', 'S2963.MC', 'ANA.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['M5S.HM']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['CLINE-B.ST', 'XX1.HM']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['VAI.WA', 'PELA.RO', 'DIABIO.MU', 'MINI.L', 'EDL.L']: possibly delisted; no timezone found

Downloading batch 2750 to 2799 / 6405

$TIS.F: possibly delisted; no timezone found
$NORDTELEKOM.BD: possibly delisted; no timezone found
$BLF.WA: possibly delisted; no timezone found
$COLK.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$AME.WA: possibly delisted; no timezone found
$FAK.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

6 Failed downloads:
['TIS.F', 'NORDTELEKOM.BD', 'BLF.WA', 'AME.WA']: possibly delisted; no timezone found
['COLK.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['FAK.SG']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 2800 to 2849 / 6405

$RAE.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$DGS.WA: possibly delisted; no timezone found
$MUN.WA: possibly delisted; no timezone found
$IFC.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$CICE.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$FU0.BE: possibly delisted; no timezone found
$BER.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$AEGA.OL: possibly delisted; no timezone found
$0M0.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$NAXY.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$MDT.WA: possibly delisted; no timezone found

11 Failed downloads:
['RAE.WA', 'CICE.RO', 'NAXY.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['DGS.WA', 'MUN.WA', 'FU0.BE', 'AEGA.OL', 'MDT.WA']: possibly delisted; no timezone found
['IFC.WA', 'BER.WA', '0M0.SG']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$S1323.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 2850 to 2899 / 6405

$GOG1.SG: possibly delisted; no timezone found
$EVO.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$VIHCA.PR: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$FPN.PA: possibly delisted; no timezone found
$EETS.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$S3612.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$OXY.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$ML2K.F: possibly delisted; no timezone found
$TCR.WA: possibly delisted; no timezone found
$ENERGYINVEST.BD: possibly delisted; no timezone found

11 Failed downloads:
['S1323.MC', 'EVO.L', 'S3612.MC']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['GOG1.SG', 'FPN.PA', 'ML2K.F', 'TCR.WA', 'ENERGYINVEST.BD']: possibly delisted; no timezone found
['VIHCA.PR']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['EETS.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['OXY.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 2900 to 2949 / 6405

$OMSE.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$KKH.WA: possibly delisted; no timezone found
$VGN.WA: possibly delisted; no timezone found
$NEWL.ST: possibly delisted; no timezone found
$PRH.WA: possibly delisted; no timezone found
$ZNWD.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
$COMBI.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$END.WA: possibly delisted; no timezone found
$HMP.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$EFE.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$WLI.WA: possibly delisted; no timezone found
$BADE.RO: possibly delisted; no timezone found
$SCIG7.MC: possibly delisted; no timezone found
$PRIMO.TL: possibly delisted; no timezone found

14 Failed downloads:
['OMSE.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['KKH.WA', 'VGN.WA', 'NEWL.ST', 'PRH.WA', 'END.WA', 'WLI.WA', 'BADE.RO', 'SCIG7.MC', 'PRIMO.TL']: possibly delisted; no timezone found
['ZNWD.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
['COMBI.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['HMP.WA', 'EFE.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 2950 to 2999 / 6405

$PBB.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$KOJAMO.HE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

2 Failed downloads:
['PBB.BE', 'KOJAMO.HE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3000 to 3049 / 6405
Downloading batch 3050 to 3099 / 6405
Downloading batch 3100 to 3149 / 6405

$AEIN.SG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$SEFER.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$VESTUM.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

3 Failed downloads:
['AEIN.SG', 'SEFER.PA', 'VESTUM.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 3150 to 3199 / 6405

$COFB.BR: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

1 Failed download:
['COFB.BR']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 3200 to 3249 / 6405

$TNIE.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['TNIE.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3250 to 3299 / 6405

$CLA.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ALREW.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

2 Failed downloads:
['CLA.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['ALREW.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 3300 to 3349 / 6405

$INLOT.AT: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['INLOT.AT']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3350 to 3399 / 6405

$FPAR.ST: possibly delisted; no timezone found
$SIM.F: possibly delisted; no timezone found
$GEA.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

3 Failed downloads:
['FPAR.ST', 'SIM.F']: possibly delisted; no timezone found
['GEA.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3400 to 3449 / 6405

$TRAD.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$NF4.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

2 Failed downloads:
['TRAD.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['NF4.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3450 to 3499 / 6405

$HXCK.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['HXCK.F']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3500 to 3549 / 6405

$BEG.L: possibly delisted; no timezone found
$PPZ.AX: possibly delisted; no timezone found

2 Failed downloads:
['BEG.L', 'PPZ.AX']: possibly delisted; no timezone found

Downloading batch 3550 to 3599 / 6405

$BFV.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$SCD.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ALEVA.BR: possibly delisted; no timezone found

3 Failed downloads:
['BFV.BE', 'SCD.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['ALEVA.BR']: possibly delisted; no timezone found

Downloading batch 3600 to 3649 / 6405

$ABL.OL: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$AGV.RO: possibly delisted; no timezone found

2 Failed downloads:
['ABL.OL']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['AGV.RO']: possibly delisted; no timezone found

Downloading batch 3650 to 3699 / 6405

$BIKE.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['BIKE.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3700 to 3749 / 6405

$DE1.HM: possibly delisted; no timezone found

1 Failed download:
['DE1.HM']: possibly delisted; no timezone found

Downloading batch 3750 to 3799 / 6405

$SPKSJF.CO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['SPKSJF.CO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3800 to 3849 / 6405

$VRAP.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['VRAP.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 3850 to 3899 / 6405
Downloading batch 3900 to 3949 / 6405

$VSURE.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

1 Failed download:
['VSURE.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 3950 to 3999 / 6405

$JHG: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")

1 Failed download:
['JHG']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")

Downloading batch 4000 to 4049 / 6405

$MHPC.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

1 Failed download:
['MHPC.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 4050 to 4099 / 6405

$01910.HK: possibly delisted; no timezone found

1 Failed download:
['01910.HK']: possibly delisted; no timezone found

Downloading batch 4100 to 4149 / 6405

$KGX.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$EVR.L: possibly delisted; no timezone found

2 Failed downloads:
['KGX.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['EVR.L']: possibly delisted; no timezone found

Downloading batch 4150 to 4199 / 6405

$8TRA.BE: possibly delisted; no timezone found

1 Failed download:
['8TRA.BE']: possibly delisted; no timezone found

Downloading batch 4200 to 4249 / 6405

$PHNX.L: possibly delisted; no timezone found

1 Failed download:
['PHNX.L']: possibly delisted; no timezone found

Downloading batch 4250 to 4299 / 6405

$01913.HK: possibly delisted; no timezone found

1 Failed download:
['01913.HK']: possibly delisted; no timezone found

Downloading batch 4300 to 4349 / 6405

$NA9.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$SYDB.CO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

2 Failed downloads:
['NA9.BE', 'SYDB.CO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 4350 to 4399 / 6405

$LUS.F: possibly delisted; no timezone found
$02233.HK: possibly delisted; no timezone found
$EIN3.F: possibly delisted; no timezone found

3 Failed downloads:
['LUS.F', '02233.HK', 'EIN3.F']: possibly delisted; no timezone found

Downloading batch 4400 to 4449 / 6405
Downloading batch 4450 to 4499 / 6405

$CGG.PA: possibly delisted; no timezone found

1 Failed download:
['CGG.PA']: possibly delisted; no timezone found

Downloading batch 4500 to 4549 / 6405

$BLV.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['BLV.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$FRS.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 4550 to 4599 / 6405

$ENDP.TO: possibly delisted; no timezone found

2 Failed downloads:
['FRS.MC']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['ENDP.TO']: possibly delisted; no timezone found

Downloading batch 4600 to 4649 / 6405

$OPAP.AT: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

1 Failed download:
['OPAP.AT']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 4650 to 4699 / 6405

$IOS.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$R3NK.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$CGCBV.HE: possibly delisted; no timezone found

3 Failed downloads:
['IOS.BE', 'R3NK.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['CGCBV.HE']: possibly delisted; no timezone found

Downloading batch 4700 to 4749 / 6405
Downloading batch 4750 to 4799 / 6405

$DGI.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

1 Failed download:
['DGI.MC']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 4800 to 4849 / 6405

$PRAE.RO: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

1 Failed download:
['PRAE.RO']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 4850 to 4899 / 6405

$MLHAY.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$STG.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$SCHST.MC: possibly delisted; no timezone found
$DEF.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$TTT.MI: possibly delisted; no timezone found

5 Failed downloads:
['MLHAY.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['STG.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['SCHST.MC', 'TTT.MI']: possibly delisted; no timezone found
['DEF.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 4900 to 4949 / 6405

$HI.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$RTC.ST: possibly delisted; no timezone found

2 Failed downloads:
['HI.MI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['RTC.ST']: possibly delisted; no timezone found

Downloading batch 4950 to 4999 / 6405

$PRIME.ST: possibly delisted; no timezone found
$BKHT.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

2 Failed downloads:
['PRIME.ST']: possibly delisted; no timezone found
['BKHT.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 5000 to 5049 / 6405

$UNX.SG: possibly delisted; no timezone found
$GPG-PREF.ST: possibly delisted; no timezone found
$CFC.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$EHEP.BD: possibly delisted; no timezone found

4 Failed downloads:
['UNX.SG', 'GPG-PREF.ST', 'EHEP.BD']: possibly delisted; no timezone found
['CFC.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 5050 to 5099 / 6405

Failed to get ticker 'FORRAS/T.BD' reason: Expecting value: line 1 column 1 (char 0)
$FORRAS/T.BD: possibly delisted; no timezone found
$SBOK.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$SOHO.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
$BEZVA-PR.PR: possibly delisted; no timezone found
$ALCYB.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$SMCRT.OL: possibly delisted; no timezone found

6 Failed downloads:
['FORRAS/T.BD', 'BEZVA-PR.PR', 'SMCRT.OL']: possibly delisted; no timezone found
['SBOK.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['SOHO.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")
['ALCYB.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 5100 to 5149 / 6405

$ARB.DU: possibly delisted; no timezone found
$ZWM.SW: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$FEN.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

3 Failed downloads:
['ARB.DU']: possibly delisted; no timezone found
['ZWM.SW']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['FEN.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 5150 to 5199 / 6405

$PIEZO.ST: possibly delisted; no timezone found
$ZOO.BE: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ALKLN.MI: possibly delisted; no timezone found
$G-COM.MI: possibly delisted; no timezone found
$DQ7.IR: possibly delisted; no timezone found

5 Failed downloads:
['PIEZO.ST', 'ALKLN.MI', 'G-COM.MI', 'DQ7.IR']: possibly delisted; no timezone found
['ZOO.BE']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 5200 to 5249 / 6405

$ALVG.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$TRAN.PA: possibly delisted; no timezone found
$INT.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$TD.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$IDE.L: possibly delisted; no timezone found

5 Failed downloads:
['ALVG.PA', 'INT.ST', 'TD.MI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['TRAN.PA', 'IDE.L']: possibly delisted; no timezone found

Downloading batch 5250 to 5299 / 6405

$EMGS.OL: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$TR61.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

2 Failed downloads:
['EMGS.OL', 'TR61.F']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 5300 to 5349 / 6405

$0VR2.L: possibly delisted; no timezone found
$MLSAG.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
$PPCGF.BE: possibly delisted; no timezone found
$EON.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$MOJ.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

5 Failed downloads:
['0VR2.L', 'PPCGF.BE']: possibly delisted; no timezone found
['MLSAG.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)
['EON.WA', 'MOJ.WA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 5350 to 5399 / 6405

$INDI.SG: possibly delisted; no timezone found
$NTW.MI: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

2 Failed downloads:
['INDI.SG']: possibly delisted; no timezone found
['NTW.MI']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 5400 to 5449 / 6405

$PAL.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

1 Failed download:
['PAL.F']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 5450 to 5499 / 6405

$ECO.MC: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$ABFAST.ST: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

2 Failed downloads:
['ECO.MC']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['ABFAST.ST']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 5500 to 5549 / 6405

$MLECE.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

1 Failed download:
['MLECE.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30)

Downloading batch 5550 to 5599 / 6405

$AFH.WA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$SLGYF.MU: possibly delisted; no timezone found
$ALTTU.PA: possibly delisted; no timezone found
$EAD.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

4 Failed downloads:
['AFH.WA', 'EAD.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['SLGYF.MU', 'ALTTU.PA']: possibly delisted; no timezone found

Downloading batch 5600 to 5649 / 6405

$ALPOU.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$SAVOS.HE: possibly delisted; no timezone found
$DNA2.L: possibly delisted; no timezone found

3 Failed downloads:
['ALPOU.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['SAVOS.HE', 'DNA2.L']: possibly delisted; no timezone found

Downloading batch 5650 to 5699 / 6405

$QLRO.ST: possibly delisted; no timezone found
$TLY.L: possibly delisted; no timezone found

2 Failed downloads:
['QLRO.ST', 'TLY.L']: possibly delisted; no timezone found

Downloading batch 5700 to 5749 / 6405

$LWL.DU: possibly delisted; no timezone found
$ANCR.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

2 Failed downloads:
['LWL.DU']: possibly delisted; no timezone found
['ANCR.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 5750 to 5799 / 6405

$C3RY.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$TET.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

2 Failed downloads:
['C3RY.F']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['TET.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 5800 to 5849 / 6405

$NTU1L.VS: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$PREC.PA: possibly delisted; no timezone found
$MPS.F: possibly delisted; no timezone found

3 Failed downloads:
['NTU1L.VS']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['PREC.PA', 'MPS.F']: possibly delisted; no timezone found

Downloading batch 5850 to 5899 / 6405

$CPP.L: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

1 Failed download:
['CPP.L']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356998400, endDate = 1782774000")

Downloading batch 5900 to 5949 / 6405

$BIGGEORGE.BD: possibly delisted; no timezone found
$GAMB: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")
$PTR1L.MU: possibly delisted; no timezone found

3 Failed downloads:
['BIGGEORGE.BD', 'PTR1L.MU']: possibly delisted; no timezone found
['GAMB']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1357016400, endDate = 1782792000")

Downloading batch 5950 to 5999 / 6405

$CS.BE: possibly delisted; no timezone found
$FORSE.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

2 Failed downloads:
['CS.BE']: possibly delisted; no timezone found
['FORSE.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 6000 to 6049 / 6405

$VARE.L: possibly delisted; no timezone found
$ETP.L: possibly delisted; no timezone found
$C21.L: possibly delisted; no timezone found
$GRF.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

4 Failed downloads:
['VARE.L', 'ETP.L', 'C21.L']: possibly delisted; no timezone found
['GRF.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 6050 to 6099 / 6405

$M3BK.F: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
$ALIMG.BR: possibly delisted; no timezone found

2 Failed downloads:
['M3BK.F']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")
['ALIMG.BR']: possibly delisted; no timezone found

Downloading batch 6100 to 6149 / 6405

$HIDDN.OL: possibly delisted; no timezone found
$WSO.F: possibly delisted; no timezone found

2 Failed downloads:
['HIDDN.OL', 'WSO.F']: possibly delisted; no timezone found

Downloading batch 6150 to 6199 / 6405

$AGXTF.L: possibly delisted; no timezone found
$DNA3.L: possibly delisted; no timezone found
$3D6.BE: possibly delisted; no timezone found
$NB2.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$VVPS.VI: possibly delisted; no timezone found

5 Failed downloads:
['AGXTF.L', 'DNA3.L', '3D6.BE', 'VVPS.VI']: possibly delisted; no timezone found
['NB2.MU']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 6200 to 6249 / 6405

$WSO.PR: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

1 Failed download:
['WSO.PR']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

Downloading batch 6250 to 6299 / 6405

$EEG1T.TL: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
$MLHMC.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$RLT.MI: possibly delisted; no timezone found
$EDI.PA: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

4 Failed downloads:
['EEG1T.TL']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356991200, endDate = 1782766800")
['MLHMC.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['RLT.MI']: possibly delisted; no timezone found
['EDI.PA']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "No data found, symbol may be delisted")

Downloading batch 6300 to 6349 / 6405

$UBK.MU: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
$ACC.L: possibly delisted; no timezone found
$ROBA.AS: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")

3 Failed downloads:
['UBK.MU', 'ROBA.AS']: possibly delisted; no price data found  (1d 2013-01-01 -> 2026-06-30) (Yahoo error = "Data doesn't exist for startDate = 1356994800, endDate = 1782770400")
['ACC.L']: possibly delisted; no timezone found

Downloading batch 6350 to 6399 / 6405

$GOODWILLPHRM.BD: possibly delisted; no timezone found

1 Failed download:
['GOODWILLPHRM.BD']: possibly delisted; no timezone found

Downloading batch 6400 to 6405 / 6405

Tickers with < 6 non-NaN Close values: ['01156.HK', '01910.HK', '01913.HK', '02233.HK', '06160.HK', '094124453.BR', '0K7K.L', '0M0.SG', '0VR2.L', '27N.DU', '3D6.BE', '4SCI.VI', '5OZ.DU', '5PG.CO', '67R.DU', '7J5.DU', '8TRA.BE', '93M.F', '9RP.SG', 'A1M.ST', 'A283WQ.DU', 'A41BVS.DU', 'A8N.MU', 'AA4.L', 'AAAP.L', 'AAQ.F', 'AAS.WA', 'ABFAST.ST', 'ABL.OL', 'ACC.L', 'ADIG.L', 'AEGA.OL', 'AEIN.SG', 'AFC.L', 'AFH.WA', 'AGCM.RO', 'AGU.MI', 'AGV.RO', 'AGXTF.L', 'ALCAB.PA', 'ALCQ.RO', 'ALCYB.PA', 'ALEVA.BR', 'ALGW.L', 'ALIMG.BR', 'ALKLN.MI', 'ALPOU.PA', 'ALREW.PA', 'ALTTU.PA', 'ALVER.PA', 'ALVG.PA', 'AME.WA', 'ANA.L', 'ANCR.L', 'ANIM.RO', 'AO9.MU', 'AQT.WA', 'ARB.DU', 'ASTG-MTF-B.ST', 'ATO.WA', 'ATOMT.PR', 'AUXI.RO', 'BADE.RO', 'BBH.L', 'BEG.L', 'BER.WA', 'BEZVA-PR.PR', 'BFV.BE', 'BGB.MU', 'BIDS.L', 'BIG.WA', 'BIG1.F', 'BIGGEORGE.BD', 'BIKE.BE', 'BKHT.BE', 'BLF.WA', 'BLV.PA', 'BOD.L', 'BONEH.HE', 'BPU.SG', 'BRH.WA', 'BSA.WA', 'BTF.RO', 'BTF.WA', 'BUF.F', 'BVX.L', 'BWIDL.OL', 'C21.L', 'C3RY.F', 'C90.DU', 'CARE.VI', 'CDR.MI', 'CDSYS.BD', 'CE.ST', 'CFC.BE', 'CFM.MI', 'CGCBV.HE', 'CGG.PA', 'CICE.RO', 'CINIS.ST', 'CIVITA.BD', 'CLA.PA', 'CLINE-B.ST', 'CMOTEC-B.ST', 'CNTA', 'COFB.BR', 'COLK.RO', 'COMBI.ST', 'COOLKLIMA.BD', 'COR.WA', 'CPP.L', 'CRP.WA', 'CS.BE', 'CST.WA', 'CTE.WA', 'CTEA.L', 'CYK.L', 'D77.BE', 'DDM.ST', 'DE.ST', 'DE1.HM', 'DEAR.ST', 'DEF.MU', 'DFH.WA', 'DGI.MC', 'DGN.WA', 'DGS.WA', 'DIABIO.MU', 'DIVI.L', 'DKE.L', 'DNA2.L', 'DNA3.L', 'DPG.WA', 'DQ7.IR', 'DRZ.WA', 'DUR.AT', 'EAD.MU', 'EBY1.SG', 'ECO.MC', 'EDI.PA', 'EDL.L', 'EEG1T.TL', 'EEMS.MI', 'EETS.RO', 'EEX.WA', 'EFCUPFFT.TL', 'EFE.WA', 'EFIN.VI', 'EGN.MI', 'EGY.WA', 'EHEP.BD', 'EIN3.F', 'ELLWEE.ST', 'ELM.WA', 'ELN.ST', 'EMGS.OL', 'END.WA', 'ENDP.TO', 'ENERGYINVEST.BD', 'EON.WA', 'ESK.WA', 'ETP.L', 'EU-SOLAR.BD', 'EVO.L', 'EVR.L', 'EVRH.L', 'FAK.SG', 'FAR.WA', 'FEN.L', 'FFI.WA', 'FFP.WA', 'FHP.L', 'FINEXT.BD', 'FING-B.ST', 'FKD.WA', 'FLG.WA', 'FMAR.RO', 'FOC.SW', 'FOMA.RO', 'FORRAS/T.BD', 'FORSE.PA', 'FPAR.ST', 'FPN.PA', 'FRS.MC', 'FU0.BE', 'G-COM.MI', 'G6P.F', 'GAMB', 'GDS.WA', 'GEA.WA', 'GG_FERR.L', 'GHIM.RO', 'GHS.L', 'GHT.WA', 'GNG.WA', 'GOG1.SG', 'GOODWILLPHRM.BD', 'GOV.WA', 'GPG-PREF.ST', 'GRE.WA', 'GREEN.RO', 'GRF.MU', 'GRL.WA', 'GRZ.WA', 'GSR.MI', 'HDW-B.ST', 'HELIO.ST', 'HELN.SW', 'HEN.WA', 'HER.WA', 'HGEA.BE', 'HI.MI', 'HID.L', 'HIDDN.OL', 'HMP.WA', 'HMSG.L', 'HOT.L', 'HRC.CO', 'HRGI.OL', 'HRL.WA', 'HRU.MU', 'HT5.SW', 'HWC.L', 'HXCK.F', 'IC8.F', 'ICE.BR', 'ICMA.RO', 'IDE.L', 'IDG.WA', 'IDM.MI', 'IDOGEN.ST', 'IFC.WA', 'IKIV.L', 'ILK1.SG', 'INDI.SG', 'INLOT.AT', 'INOX.RO', 'INT.ST', 'IOS.BE', 'IRABAS.CO', 'IRL.WA', 'IRP.HM', 'ISD.WA', 'JHG', 'JMG.L', 'JMI.L', 'K2LT.VS', 'KDEV.ST', 'KGX.BE', 'KIBO.L', 'KKH.WA', 'KLK.WA', 'KMB.WA', 'KMCP.OL', 'KOJAMO.HE', 'L03.MU', 'L3D.DU', 'LA2.BE', 'LASIA.MI', 'LAUR.ST', 'LBH1.MU', 'LBRT.L', 'LITO.RO', 'LSAI.L', 'LUO.WA', 'LUS.F', 'LWL.DU', 'M14.MU', 'M3BK.F', 'M5S.HM', 'MAHA-A.ST', 'MASHUP.ST', 'MAZ.WA', 'MB7.MU', 'MCT.L', 'MDT.WA', 'MEBY.RO', 'MECA.RO', 'MECE.RO', 'MECP.RO', 'MET.RO', 'MHPC.L', 'MIG.WA', 'MINI.L', 'ML2K.F', 'MLARI.PA', 'MLARR.LS', 'MLASO.PA', 'MLAST.PA', 'MLBAR.PA', 'MLCAN.PA', 'MLCOE.PA', 'MLCOT.PA', 'MLECE.PA', 'MLEDS.PA', 'MLEFA.PA', 'MLGLA.PA', 'MLGSH.LS', 'MLHAY.PA', 'MLHMC.PA', 'MLIME.PA', 'MLINM.PA', 'MLIPO.PA', 'MLISP.PA', 'MLJDL.PA', 'MLMAC.LS', 'MLMCA.PA', 'MLMIV.PA', 'MLMR.LS', 'MLNDG.PA', 'MLNOX.PA', 'MLOKP.PA', 'MLORB.PA', 'MLSAG.PA', 'MLSPI.PA', 'MLUAV.PA', 'MLVRE.PA', 'MLVRF.PA', 'MODEL-B.ST', 'MOJ.WA', 'MOV-BTU.ST', 'MPH.L', 'MPK.AT', 'MPS.F', 'MRG.WA', 'MTE.WA', 'MUN.WA', 'MYNZ', 'N4P.L', 'NA9.BE', 'NAXY.RO', 'NB2.MU', 'NBA.MI', 'NBDD.L', 'NBZ.AS', 'NEWL.ST', 'NF4.BE', 'NN6.HM', 'NORD.CO', 'NORDTELEKOM.BD', 'NR.MI', 'NSCI.L', 'NTQ.L', 'NTU1L.VS', 'NTW.MI', 'O3PNRS.BD', 'OAB.HM', 'OCTP.L', 'OMSE.RO', 'OP', 'OPAP.AT', 'OXY.WA', 'PAC.WA', 'PACEU.AS', 'PAL.F', 'PAL.L', 'PBB.BE', 'PDA.F', 'PELA.RO', 'PGG.WA', 'PHLOG-B.ST', 'PHNX.L', 'PIEZO.ST', 'PIIPPO.HE', 'PIX.WA', 'PMA.WA', 'PPCGF.BE', 'PPG.WA', 'PPZ.AX', 'PRAE.RO', 'PRDI.RO', 'PREC.PA', 'PRH.WA', 'PRIME.ST', 'PRIMO.TL', 'PRIN.RO', 'PSH.WA', 'PTE.WA', 'PTR1L.MU', 'PXOG.L', 'Q9U.DU', 'QB7.BE', 'QLRO.ST', 'QRT.WA', 'QUART.ST', 'R1B.MU', 'R3NK.BE', 'RAE.WA', 'RAP.PA', 'RAY.WA', 'RCVR.BE', 'RECSI.OL', 'REDC.L', 'REE.L', 'REG.WA', 'RGL.WA', 'RGM.L', 'RIIC.L', 'RLF.SW', 'RLIINV.CO', 'RLT.MI', 'ROBA.AS', 'ROBUS.TL', 'RORA.PA', 'RTC.BE', 'RTC.ST', 'RTOP.L', 'RY8.DU', 'S0063.MC', 'S0819.MC', 'S0951.MC', 'S1013.MC', 'S1146.MC', 'S1323.MC', 'S1420.MC', 'S1436.MC', 'S2464.MC', 'S2490.MC', 'S2700.MC', 'S2856.MC', 'S2963.MC', 'S3448.MC', 'S3518.MC', 'S3612.MC', 'S3652.MC', 'S3700.MC', 'S3740.MC', 'SAVOS.HE', 'SBDS.L', 'SBOK.ST', 'SCASM.MC', 'SCD.RO', 'SCFRS.MC', 'SCHST.MC', 'SCIBH.MC', 'SCIG2.MC', 'SCIG5.MC', 'SCIG7.MC', 'SCLIS.MC', 'SCM.MI', 'SCORE.MC', 'SCSOL.MC', 'SCWEL.MC', 'SEC.PA', 'SEFER.PA', 'SGD.WA', 'SHY.WA', 'SIEP.RO', 'SILEON.ST', 'SIM.F', 'SIV.L', 'SKY.WA', 'SL021.MC', 'SL051.MC', 'SLB.MU', 'SLGYF.MU', 'SLT.WA', 'SMART-SDB.ST', 'SMCRT.OL', 'SOHO.L', 'SPARK.CO', 'SPEQT.ST', 'SPKSJF.CO', 'STG.MU', 'SWEF.L', 'SYDB.CO', 'TALD.RO', 'TBX0.BE', 'TCBP', 'TCR.WA', 'TD.MI', 'TERA.RO', 'TET.L', 'THRG.L', 'TIGH.RO', 'TIS.F', 'TLY.L', 'TNIE.BE', 'TNT.WA', 'TR61.F', 'TRAD.ST', 'TRAN.PA', 'TRH.MC', 'TTT.MI', 'TWEP.MI', 'UBK.MU', 'UBM.MI', 'UNX.SG', 'UPRR.RO', 'URA.L', 'VAI.WA', 'VALBERG.BD', 'VARE.L', 'VERI.ST', 'VESTUM.ST', 'VFA.WA', 'VGN.WA', 'VIHCA.PR', 'VMED.DU', 'VMX.WA', 'VQLA.MU', 'VRAP.PA', 'VRL.DU', 'VRS.L', 'VSC.F', 'VSURE.ST', 'VVPR', 'VVPS.VI', 'WLI.WA', 'WMC.MI', 'WRE.WA', 'WSO.F', 'WSO.PR', 'XDD.WA', 'XK7.SG', 'XX1.HM', 'YAYTRD.ST', 'YTME.SW', 'ZICC.ST', 'ZNWD.L', 'ZOO.BE', 'ZS4.MU', 'ZWM.SW']
Saved filtered data to prices_backfill.csv
Saved missing/too short tickers to prices_missing.csv

Final: 5883 tickers with >= 6 data, 523 with too little data, 0 never returned any data.

In [61]:
# %% Section 2b — load prices
symbol_to_id  = dict(zip(ok['yahoo_symbol'], ok['company_id']))
symbol_to_ccy = dict(zip(ok['yahoo_symbol'], ok['currency']))
load_prices(con, filtered_df, symbol_to_id, symbol_to_ccy)

prices upserted: 20,599,184 rows, 5,883 companies

In [75]:
filtered_df.head()

Price       Date  Ticker  Adj Close  Close  High  Low  Open  Volume
0     2013-01-01   3IN.L        NaN    NaN   NaN  NaN   NaN     NaN
1     2013-01-01  A2A.MI        NaN    NaN   NaN  NaN   NaN     NaN
2     2013-01-01  AC5.MI        NaN    NaN   NaN  NaN   NaN     NaN
3     2013-01-01  ACE.MI        NaN    NaN   NaN  NaN   NaN     NaN
4     2013-01-01    AMCR        NaN    NaN   NaN  NaN   NaN     NaN

In [62]:
print(pd.read_sql("""
    SELECT COUNT(*) rows,
           COUNT(DISTINCT company_id) firms,
           MIN(date) first_date, MAX(date) last_date
    FROM prices
""", con).to_string(index=False))

    rows  firms first_date  last_date
20599184   5883 2013-01-01 2026-06-29

In [64]:
# Create a new table to indicate which companies are mapped
# %% create symbol_coverage (standalone — does NOT touch prices)
con.executescript("""
CREATE TABLE IF NOT EXISTS symbol_coverage (
    company_id   TEXT PRIMARY KEY,
    ticker       TEXT, exchange TEXT, yahoo_symbol TEXT, currency TEXT,
    status       TEXT, universe TEXT,
    FOREIGN KEY (company_id) REFERENCES master_company_list(company_id)
);
""")

In [69]:
cov = build_symbol_coverage(con, ok, unmapped)

symbol_coverage: 8,288 rows
status
mapped_loaded        5883
unmapped_exchange    1773
mapped_no_data        523
no_ticker             109

In [76]:
cov_counts = pd.read_sql("""
    SELECT company_id,
           COUNT(*)                                    AS n_rows,
           SUM(CASE WHEN close IS NOT NULL THEN 1 END) AS n_real
    FROM prices
    WHERE date >= '2019-01-01'
    GROUP BY company_id
""", con)

print(f"firms: {len(cov_counts):,}")
print("\nn_real (non-null closes) distribution:")
print(cov_counts['n_real'].describe(percentiles=[.01,.05,.10,.25,.50]).to_string())
print(f"\nfirms with < 250 real: {(cov_counts['n_real'] < 250).sum():,}")
print(f"firms with < 500 real: {(cov_counts['n_real'] < 500).sum():,}")
print(f"\nrow-count vs real-count gap (padding):")
print((cov_counts['n_rows'] - cov_counts['n_real']).describe().to_string())

firms: 5,883

n_real (non-null closes) distribution:
count    5862.000000
mean     1679.153702
std       435.856958
min         6.000000
1%        176.610000
5%        546.050000
10%      1030.100000
25%      1848.250000
50%      1891.000000
max      1918.000000

firms with < 250 real: 100
firms with < 500 real: 239

row-count vs real-count gap (padding):
count    5862.000000
mean      261.273456
std       435.812186
min         5.000000
25%        42.000000
50%        54.000000
75%        91.750000
max      1935.000000

What padding is:

- when yf.download pulls a batch, it builds one shared date index = the union of every trading day any ticker in that batch traded. Any ticker that didn't trade on a given day gets a NaN row on that day. So a firm that IPO'd in 2021, or barely trades, or whose exchange had a holiday, gets NaN-filled rows. Your row-count query counted those NaN rows as if they were real data. The row-vs-real gap (median 54, max 1,935) is the padding, measured directly.

Some observations for n_real (non-null rows):
- A firm that IPO'd in 2022 has ~900 real days, all contiguous --> need to keep
- A firm that's illiquid/suspended has ~900 real days scattered with holes throughout (unreliable or highly illiquid firms)

Thus, the metric that is more informative is density = real days ÷ days it could have traded while listed.

**Late-IPO firm ≈ 1.0 (keep); gappy firm ≈ 0.5 (drop); filter on density not raw count**

In [5]:
# %% remove NaN-close padding rows from prices (reversible from backfill CSV)
before = pd.read_sql("SELECT COUNT(*) n FROM prices", con)['n'][0]
con.execute("DELETE FROM prices WHERE close IS NULL")
con.commit()
after = pd.read_sql("SELECT COUNT(*) n FROM prices", con)['n'][0]
print(f"deleted {before-after:,} NaN rows;  {after:,} real rows remain")

deleted 0 NaN rows;  15,654,648 real rows remain

In [78]:
# %% per-firm coverage + density in the 2019+ window
diag = pd.read_sql("""
    SELECT company_id, COUNT(*) AS n_real,
           MIN(date) AS first_real, MAX(date) AS last_real
    FROM prices WHERE date >= '2019-01-01'
    GROUP BY company_id
""", con)

In [79]:
# market calendar = every date any firm really traded, in window
mkt = pd.read_sql("SELECT DISTINCT date FROM prices WHERE date >= '2019-01-01'",
                  con)['date'].sort_values().reset_index(drop=True)

mkt_idx = {d: i for i, d in enumerate(mkt)}

# expected days = market-calendar days between a firm's first and last real trade
diag['expected'] = diag.apply(
    lambda r: mkt_idx[r['last_real']] - mkt_idx[r['first_real']] + 1, axis=1)
diag['density'] = diag['n_real'] / diag['expected']

print(f"firms with real data in window: {len(diag):,}")
print("\ndensity distribution:")
print(diag['density'].describe(percentiles=[.01,.05,.10,.25]).to_string())
print(f"\ndensity < 0.90: {(diag['density'] < 0.90).sum():,}")
print(f"density < 0.95: {(diag['density'] < 0.95).sum():,}")
print(f"n_real   < 500: {(diag['n_real'] < 500).sum():,}")
print("\nlate starters (first_real > 2020, but dense >0.95):")
print((( diag['first_real'] > '2020-01-01') & (diag['density'] > 0.95)).sum())

firms with real data in window: 5,862

density distribution:
count    5862.000000
mean        0.963620
std         0.057962
min         0.030769
1%          0.878555
5%          0.952539
10%         0.958585
25%         0.962936
50%         0.969247
max         1.000000

density < 0.90: 63
density < 0.95: 147
n_real   < 500: 239

late starters (first_real > 2020, but dense >0.95):
1178

In [80]:
elig = (diag['density'] >= 0.90) & (diag['n_real'] >= 250)
print(f"eligible:   {elig.sum():,}")
print(f"excluded:   {(~elig).sum():,}")
print("\nexcluded breakdown:")
print(f"  fails density (<0.90): {(diag['density'] < 0.90).sum():,}")
print(f"  fails n_real  (<250):  {(diag['n_real'] < 250).sum():,}")
print(f"  fails both:            {((diag['density']<0.90) & (diag['n_real']<250)).sum():,}")

# peek at what we'd drop — sanity check they're really junk
print("\nsample of excluded firms:")
print(diag[~elig].merge(
    pd.read_sql('SELECT company_id, company_name, exchange FROM master_company_list', con),
    on='company_id')[['company_name','exchange','n_real','density']]
    .sort_values('density').head(15).to_string(index=False))

eligible:   5,711
excluded:   151

excluded breakdown:
  fails density (<0.90): 63
  fails n_real  (<250):  100
  fails both:            12

sample of excluded firms:
                      company_name                   exchange  n_real  density
                       FIMARO S.A.   Bucharest Stock Exchange      16 0.030769
                     SC ALBAPAM SA   Bucharest Stock Exchange      30 0.057692
                        PRACTIC SA   Bucharest Stock Exchange      52 0.096296
CONSTRUCTII FEROVIARE CRAIOVA S.A.   Bucharest Stock Exchange      67 0.117958
    INVERSIONES HERRERO, SA, SICAV            Bolsa de Madrid     177 0.119595
                        COMALEX SA   Bucharest Stock Exchange      77 0.143657
     GSTAAD INVERSIONES, SICAV, SA Bolsa de Valores de Bilbao     241 0.156291
               SIDICLEAR SICAV SA.            Bolsa de Madrid     342 0.267396
   PENSIONINVEST CAPITAL SICAV SA. Bolsa de Valores de Bilbao     297 0.268293
       FONDUL OAMENILOR DE AFACERI   Bucharest Stock Exchange     162 0.276923
     MANATI INVERSIONES, SICAV, SA Bolsa de Valores de Bilbao     373 0.284299
     INVERSIONES TAMBORE SICAV SA.            Bolsa de Madrid     460 0.308518
                FORALEX, SICAV, SA         Bolsa de Barcelona     513 0.344758
       FEGON INVERSIONES SICAV, SA            Bolsa de Madrid     517 0.346747
    ABRIL 28 INVESTMENT, SICAV, SA         Bolsa de Barcelona     517 0.346747

In [83]:
# %% add eligibility flag to symbol_coverage (post-pull filter: density>=0.90 AND n_real>=250)
con.execute("ALTER TABLE symbol_coverage ADD COLUMN eligible INTEGER DEFAULT 0")

# create a set of company id with eligible data:
elig_ids = set(diag[(diag['density'] >= 0.90) & (diag['n_real'] >= 250)]['company_id'])

# populate rows in database (only matched eligible company ids):
con.executemany("UPDATE symbol_coverage SET eligible=? WHERE company_id=?",
                [(1 if c in elig_ids else 0, c) for c in
                 pd.read_sql("SELECT company_id FROM symbol_coverage", con)['company_id']])
con.commit()

In [84]:
# 
print(pd.read_sql("""
    SELECT status, eligible, COUNT(*) n
    FROM symbol_coverage GROUP BY status, eligible ORDER BY status, eligible
""", con).to_string(index=False))

           status  eligible    n
    mapped_loaded         0  172
    mapped_loaded         1 5711
   mapped_no_data         0  523
        no_ticker         0  109
unmapped_exchange         0 1773

In [91]:
# the 5,711-firm analysis panel, any time you need it
panel = pd.read_sql("""
    SELECT p.company_id, p.date, p.close, p.currency, p.high, p.low, p.open, p.volume
    FROM prices p
    JOIN symbol_coverage s ON s.company_id = p.company_id
    WHERE s.eligible = 1 AND p.date >= '2019-01-01'
""", con)

### Fx Pull

why do we need fx? 
Pulled prices are in local currency, and we aim to convert to common currency (EUR); we need to adopt a by-day fx rate for read-time conversion.

Goal: one EUR exchange rate per (currency, date) so read-time conversion can turn local prices into EUR. eur_price = local_price / rate_per_eur.
There is a total currency mix of ~17, but EUR itself needs no rate (it's the base), so we pull the ~13 non-EUR ones.

In [95]:
# BP plc: ~£4-5/share. If close is ~450, it's pence (GBp). If ~4.5, it's pounds.
chk = pd.read_sql("""
    SELECT s.company_id, p.date, p.close, p.currency
    FROM prices p JOIN symbol_coverage s ON s.company_id=p.company_id
    WHERE s.ticker IN ('BP.','ULVR','AZN') AND p.date >= '2026-06-01'
    ORDER BY p.date DESC LIMIT 10
""", con)

print(chk.to_string(index=False))

  company_id       date        close currency
GB00BVZK7T90 2026-06-29  4580.000000      GBp
GB0007980591 2026-06-29   472.700012      GBp
GB0009895292 2026-06-29 14298.000000      GBp
GB00BVZK7T90 2026-06-26  4600.500000      GBp
GB0007980591 2026-06-26   469.399994      GBp
GB0009895292 2026-06-26 14318.000000      GBp
GB00BVZK7T90 2026-06-25  4579.500000      GBp
GB0007980591 2026-06-25   480.850006      GBp
GB0009895292 2026-06-25 14062.000000      GBp
GB00BVZK7T90 2026-06-24  4544.000000      GBp

In [98]:
ccys = currencies_in_universe(con)
print(f"{len(ccys)} currencies:", ccys)

15 currencies: ['AUD', 'CAD', 'CHF', 'CZK', 'DKK', 'GBP', 'HUF', 'ILS', 'ISK', 'NOK', 'PLN', 'RON', 'SEK', 'USD', 'ZAR']

In [99]:
# %% Section 3b — pull FX (~13 symbols, a minute or two)
fx_df = fetch_fx(ccys)
print(f"\npulled {len(fx_df):,} rows")
print(fx_df.groupby('currency')['date'].agg(['count', 'min', 'max']).to_string())

pulled 52,689 rows
          count         min         max
currency
AUD        3513  2013-01-01  2026-06-29
CAD        3513  2013-01-01  2026-06-29
CHF        3513  2013-01-01  2026-06-29
CZK        3513  2013-01-01  2026-06-29
DKK        3513  2013-01-01  2026-06-29
GBP        3513  2013-01-01  2026-06-29
HUF        3513  2013-01-01  2026-06-29
ILS        3513  2013-01-01  2026-06-29
ISK        3511  2013-01-01  2026-06-29
NOK        3513  2013-01-01  2026-06-29
PLN        3513  2013-01-01  2026-06-29
RON        3511  2013-01-01  2026-06-29
SEK        3513  2013-01-01  2026-06-29
USD        3511  2013-01-01  2026-06-29
ZAR        3513  2013-01-01  2026-06-29

In [100]:
# %% Section 3c — load into fx_rates
load_fx(con, fx_df)

fx upserted: 52,689 rows, 15 currencies

In [101]:
# sanity: row counts + a spot rate per currency
print(pd.read_sql("""
    SELECT currency, COUNT(*) n, MIN(date) first, MAX(date) last
    FROM fx_rates GROUP BY currency ORDER BY currency
""", con).to_string(index=False))

currency    n      first       last
     AUD 3513 2013-01-01 2026-06-29
     CAD 3513 2013-01-01 2026-06-29
     CHF 3513 2013-01-01 2026-06-29
     CZK 3513 2013-01-01 2026-06-29
     DKK 3513 2013-01-01 2026-06-29
     GBP 3513 2013-01-01 2026-06-29
     HUF 3513 2013-01-01 2026-06-29
     ILS 3513 2013-01-01 2026-06-29
     ISK 3511 2013-01-01 2026-06-29
     NOK 3513 2013-01-01 2026-06-29
     PLN 3513 2013-01-01 2026-06-29
     RON 3511 2013-01-01 2026-06-29
     SEK 3513 2013-01-01 2026-06-29
     USD 3511 2013-01-01 2026-06-29
     ZAR 3513 2013-01-01 2026-06-29

In [102]:
print(pd.read_sql("""
    SELECT date, rate_per_eur FROM fx_rates
    WHERE currency='GBP' ORDER BY date DESC LIMIT 3
""", con).to_string(index=False))

      date  rate_per_eur
2026-06-29       0.86270
2026-06-26       0.86133
2026-06-25       0.86245

### Splits Data

note: we have indicated auto_adjust to Flase when pulling price data via yahoo finance. This is because prices oulled with auto adjusting by default would not update prior downloaded data that have been stored in our database. INSERT OR IGNORE would never rewrite the old rows → silent drift.

Raw prices never change. €50.20 on 2013-05-01 is €50.20 forever. So storing raw makes INSERT OR IGNORE genuinely idempotent, and we compute the adjustment fresh at read-time from a separate splits table


Feature engineering flow:
- store raw OHLCV (done) + store split events (this step)
- apply the adjustment when you pull the panel (feature stage)
- The splits table is small; most firms have zero or one split in the window — so this is cheap.

adjustment methods
- back-adjust the pre-split prices by the split ratio so the series is continuous
- Multiply every price before the split by the ratio's inverse:

In [31]:
# %% create corporate_actions table
con.executescript("""
CREATE TABLE IF NOT EXISTS corporate_actions (
    company_id  TEXT NOT NULL, date TEXT NOT NULL, action_type TEXT NOT NULL,
    value REAL, source TEXT DEFAULT 'yfinance',
    PRIMARY KEY (company_id, date, action_type),
    FOREIGN KEY (company_id) REFERENCES master_company_list(company_id)
);
""")
print("corporate_actions created")

corporate_actions created

In [32]:
# %% Section 4a — build the symbol->id map for ELIGIBLE firms only
from src.actions_pull import fetch_actions, load_actions

elig_syms = pd.read_sql("""
    SELECT yahoo_symbol, company_id
    FROM symbol_coverage
    WHERE eligible = 1 AND yahoo_symbol IS NOT NULL
""", con)

symbol_to_id = dict(zip(elig_syms['yahoo_symbol'], elig_syms['company_id']))

print(f"pulling actions for {len(symbol_to_id):,} eligible firms")

pulling actions for 5,711 eligible firms

In [34]:
actions_df = fetch_actions(symbol_to_id,
                           checkpoint_csv=str(ROOT / 'data' / 'raw' / 'actions_checkpoint.csv'))

to fetch: 5,711 firms

  620/5711  (10%)  actions so far: 10,163

AEDES.MI: auto_adjust failed with unsupported operand type(s) for /: 'str' and 'float'

  5711/5711  (100%)  actions so far: 79,022
failed for 4 symbols (first 10): ['YIRG.MC', 'PRE.WA', 'SCAML.MC', 'TTS.RO']

total: 79,022 actions: 2,823 splits, 76,199 dividends

In [42]:
actions_df

         company_id        date action_type  value
0      AT000000STR1  2008-06-27    dividend   0.55
1      AT000000STR1  2009-06-26    dividend   0.55
2      AT000000STR1  2010-06-25    dividend   0.50
3      AT000000STR1  2011-06-17    dividend   0.55
4      AT000000STR1  2012-06-22    dividend   0.60
...             ...         ...         ...    ...
79017  SE0017083272  2025-08-15    dividend   0.16
79018  SE0017083272  2025-11-14    dividend   0.16
79019  SE0017083272  2026-02-13    dividend   0.16
79020  SE0017083272  2026-05-21    dividend   0.18
79021  SE0017083272  2026-08-14    dividend   0.18

[79022 rows x 4 columns]

In [35]:
# %% Section 4c — load + sanity
load_actions(con, actions_df)

actions upserted: 79,022 rows, 4,205 companies

In [39]:
print(pd.read_sql("""
    SELECT action_type, COUNT(*) n, COUNT(DISTINCT company_id) firms
    FROM corporate_actions
    GROUP BY action_type
""", con))

  action_type      n  firms
0    dividend  76199   3769
1       split   2823   1732

In [43]:
# 1. Split ratios should be sensible (mostly 2.0, 3.0, 0.5 for reverse, etc.)
print(pd.read_sql("""
    SELECT value AS split_ratio, COUNT(*) n
    FROM corporate_actions WHERE action_type='split'
    GROUP BY value ORDER BY n DESC LIMIT 10
""", con).to_string(index=False))

 split_ratio   n
        2.00 393
        0.10 263
        5.00 210
       10.00 190
        4.00 184
        3.00 150
        0.01 140
        1.10  78
        0.20  70
        0.05  65

In [44]:
# 2. A known splitter as a spot-check — any large firm you recognize
print(pd.read_sql("""
    SELECT m.company_name, c.date, c.value
    FROM corporate_actions c
    JOIN master_company_list m ON m.company_id = c.company_id
    WHERE c.action_type='split'
    ORDER BY c.date DESC LIMIT 8
""", con).to_string(index=False))

                        company_name       date     value
                11 88 0 SOLUTIONS AG 2026-08-10  0.200000
               ACCELER8 VENTURES PLC 2026-08-07  4.041100
                 SUNDELL ESTATE NYRT 2026-08-04 20.000000
                      REDCENTRIC PLC 2026-07-29  0.050000
                   BANCA PROFILO SPA 2026-07-27  0.100000
PARTNER AEROSPACE & DEFENSE GROUP SA 2026-07-27  0.010000
        AGROLAND BUSINESS SYSTEM S.A 2026-07-27  1.031250
                 TRINITY BIOTECH PLC 2026-07-24  0.033333